### ISSUE TITLE
Guidebook TODOs

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/GuideME#5]
- [x] AppliedEnergistics/Applied-Energistics-2#6873
- [x] AppliedEnergistics/Applied-Energistics-2#7051
- [x] Fix recipe boxes if the title is too long (I.e. small shapeless crafting recipes)
- [x] AppliedEnergistics/Applied-Energistics-2#6870
- [x] AppliedEnergistics/Applied-Energistics-2#6868
- [x] AppliedEnergistics/Applied-Energistics-2#6871
- [x] Allow the navigation sidebar to be pinned
- [x] All blocks and items have pages
- [x] Duplicate item ids in the item id index have been cleaned up (required for `<ItemLink .../>` to not be ambiguous
- [x] AppliedEnergistics/Applied-Energistics-2#6991
- [x] AppliedEnergistics/Applied-Energistics-2#7079
- [x] AppliedEnergistics/Applied-Energistics-2#7080
- [x] AppliedEnergistics/Applied-Energistics-2#6854
- [x] AppliedEnergistics/Applied-Energistics-2#7100
- [x] AppliedEnergistics/Applied-Energistics-2#7110 
- [x] AppliedEnergistics/Applied-Energistics-2#7114
- [x] AppliedEnergistics/Applied-Energistics-2#7115
- [x] AppliedEnergistics/Applied-Energistics-2#7128
- [ ] AppliedEnergistics/GuideME#6
- [x] AppliedEnergistics/Applied-Energistics-2#7129
